name: nutancollegeofnursing
recipe: drupal9
config:
  webroot: web
services:
  appserver:
    type: php:8.1
  phpmyadmin:
    type: phpmyadmin
    hosts:
      - database
proxy:
  appserver:
    - nutancollegeofnursing.lndo.site
  phpmyadmin:
    - phpmyadmin.nutancollegeofnursing.lndo.site

