_core:
  default_config_hash: R4IF-ClDHXxblLcG0L7MgsLvfBIMAvi_skumNFQwkDc
module:
  actions_permissions: 0
  address: 0
  addtoany: 0
  admin_toolbar: 0
  admin_toolbar_tools: 0
  automated_cron: 0
  backup_migrate: 0
  barcodes: 0
  big_pipe: 0
  block: 0
  block_classes: 0
  block_content: 0
  breakpoint: 0
  captcha: 0
  ckeditor5: 0
  colorbox: 0
  comment: 0
  commerce: 0
  commerce_cart: 0
  commerce_checkout: 0
  commerce_instamojo: 0
  commerce_log: 0
  commerce_migrate: 0
  commerce_migrate_commerce: 0
  commerce_number_pattern: 0
  commerce_order: 0
  commerce_payment: 0
  commerce_price: 0
  commerce_product: 0
  commerce_store: 0
  conditional_fields: 0
  config: 0
  contextual: 0
  crop: 0
  csv_serialization: 0
  ctools: 0
  datetime: 0
  dblog: 0
  draggableviews: 0
  dynamic_page_cache: 0
  editor: 0
  email_registration: 0
  entity: 0
  entity_reference_revisions: 0
  entityreference_filter: 0
  fb_likebox: 0
  field: 0
  field_group: 0
  field_group_migrate: 0
  field_permissions: 0
  field_ui: 0
  file: 0
  filter: 0
  fontawesome: 0
  fontawesome_iconpicker_widget: 0
  google_analytics: 0
  help: 0
  history: 0
  image: 0
  image_captcha: 0
  image_widget_crop: 0
  imce: 0
  inline_entity_form: 0
  jcarousel: 0
  jquery_ui: 0
  jquery_ui_accordion: 0
  libraries: 0
  link: 0
  login_destination: 0
  markup: 0
  menu_link_content: 0
  menu_per_role: 0
  menu_ui: 0
  metatag: 0
  metatag_facebook: 0
  metatag_favicons: 0
  metatag_google_cse: 0
  metatag_open_graph: 0
  metatag_views: 0
  migrate: 0
  migrate_drupal: 0
  migrate_drupal_ui: 0
  migrate_plus: 0
  migrate_tools: 0
  migrate_upgrade: 0
  mysql: 0
  node: 0
  options: 0
  page_cache: 0
  path: 0
  path_alias: 0
  profile: 0
  registration_role: 0
  rest: 0
  rules: 0
  search: 0
  serialization: 0
  shortcut: 0
  site_verify: 0
  state_machine: 0
  stringoverrides: 0
  superfish: 0
  system: 0
  taxonomy: 0
  telephone: 0
  text: 0
  token: 0
  toolbar: 0
  tour: 0
  twig_tweak: 0
  typed_data: 0
  user: 0
  user_registrationpassword: 0
  view_marquee: 0
  views_accordion: 0
  views_bulk_operations: 0
  views_data_export: 0
  views_migration: 0
  views_slideshow: 0
  views_slideshow_cycle: 0
  views_ui: 0
  webform: 0
  webform_migrate: 0
  webform_node: 0
  webform_ui: 0
  weight: 0
  extlink: 1
  pathauto: 1
  views: 10
  paragraphs: 11
  custom_search: 50
  standard: 1000
theme:
  olivero: 0
  claro: 0
  stable9: 0
  bootstrap5: 0
  ncn: 0
profile: standard
